### ISSUE TITLE
Consolidating Categories

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-companies#252]
We have _a lot_ of categories, too many.   Should we consolidate the categories into a smaller set with broader categories?  If we do, should we add in the concept of tags?

@stevedomin any thoughts?

**Comment by stevedomin** [comment]
@doomspork sorry for not responding earlier, been travelling a lot.

I guess my first question would be: what do we use categories for?

**Comment by doomspork** [comment]
No worries @stevedomin!  I've been away a lot myself lately.  The categories are used for organization.  Perhaps tags would be better suited for that?

**Comment by doomspork** [comment]
@burden and @ybur-yug2 either of you have any thoughts?  I know we've briefly discussed this before.

**Comment by stevedomin** [comment]
@doomspork sorry my question wasn't very clear. I know where we used them but I'm more interested in why we have them in the first place? 

In the markdown we used it for grouping companies but now they're listed alphabetically and we don't offer any kind of sorting/grouping.

I guess tags would work here but I worry it would become a mess.

How do we want users to use them? What do we want to highlight with these categories/tags?

**Comment by doomspork** [comment]
Ah ha!  Sorry about that @stevedomin.  I'm trying to think of a new UI for the site that would allow you to sort companies by an industry, which is essentially what categories are supposed to be.

**Comment by stevedomin** [comment]
@doomspork makes sense. Should we use a list like this one then? https://gist.github.com/mbejda/19012b99a12e9d014389

Or any other standardised list of industry?

**Comment by doomspork** [comment]
@stevedomin this is _awesome_, how the heck did you find that?  This would be a fantastic list to use.

**Comment by stevedomin** [comment]
Not sure how I found it tbh :)

Shall I make a PR with this new list?

**Comment by doomspork** [comment]
Please do @stevedomin!

**Comment by stevedomin** [comment]
Love the new page @doomspork !!! <3

**Comment by doomspork** [comment]
Thank you @stevedomin, @burden did most of the layout work!
