### ISSUE TITLE
Github links are giving 404

### ISSUE THREAD

**Issue by rhnonose** [doomspork/elixir-companies#288]
All (as far as I checked) company github links are returning `404`.

Apparently, the company layout is expecting the github field to be a user/org and it's appending to `http://github.com/`, resulting in a broken url (homepage's first company's github is `https://github.com/https://github.com/ScriptDrop?language=elixir`).

**Comment by doomspork** [comment]
Thank you @rhnonose!  I'll take a peek right now 👍
