### ISSUE TITLE
Filter/search on location?

### ISSUE THREAD

**Issue by Tuxified** [doomspork/elixir-companies#296]
It's currently possible to browse by industry, but I think it might also make sense to add location as a filter so folks can see which companies can be found in their country/neighbourhood? What do you folks think, would that be a good feature?

**Comment by Nezteb** [comment]
I came here to post this same issue. Even just having a page that lists all of the unique locations in the source YAML file and which companies are in those locations would be good.

**Comment by doomspork** [comment]
This is a great idea.  Let's talk it over.  What would we want the final product to look like?

**Comment by doomspork** [comment]
We've updated the site to be powered by Phoenix, I think this issue, and #354, should be easier to tackle now. Happy to discuss this further 👍

**Comment by Nezteb** [comment]
I'll come up with a mockup in the next few days! Also check to see how difficult it would be to implement myself. 😄

**Comment by doomspork** [comment]
@Nezteb I'm happy to brainstorm some approaches with you and do some pair-programming if our schedules overlap 😁

Throwing out some ideas:

We add PostGIS to the DB and a lat/lon for every business then plot them on a map.

**Comment by doomspork** [comment]
Conversation for implementation can be found on #494
