### ISSUE TITLE
Too many industries

### ISSUE THREAD

**Issue by michalmuskala** [doomspork/elixir-companies#337]
The industries list is so large, some of them don't show on the drop-down. Right now, the list ends for me with "Sports"

<img width="913" alt="screen shot 2018-07-16 at 18 24 25" src="https://user-images.githubusercontent.com/477062/42770812-8932fdf8-8925-11e8-8248-2fe36f9963bb.png">

It seems there are also some almost duplicates with "Marketing/Sales" and "Marketing/Advertisement/Sales" or "Marketplace" and "Marketplaces".

**Comment by doomspork** [comment]
I agree.  I've slowly been working through this list to consolidate the industries.  Any ideas would be greatly appreciated 😁

**Comment by lackac** [comment]
In the meantime I submitted a fix in #352 for showing all industries in the dropdown.

**Comment by OmanF** [comment]
Top of my head ideas on consolidating:
1. `Blockchain & Fintech`, `Financial services`, `Financial technologies`, `Insurance`, `Payment` --> `Financial services` (If you can't figure out `Payment` is *a* financial service, as a recruiter, I wouldn't like you to submit your CV my way. Seriously. And as a candidate, I really don't care if you're financial technology or service... I want to do cool shit with Elixir that has a financial aspect to it).
2. `E-Commerce`, `Marketing/Advertising/Sales`, `Marketing/Sales` (yes, you have these two distinct categories... check it out yourself), `Marketplaces`, `Online ordering`, `Retail industry` --> `E-Commerce` (though I'd style it `eCommerce`, but that's the least of your worries).
3. `Cannabis`, `Child care`, `Family`, `Health/Fitness`, `Healthcare` --> `Healthcare & Family` (for me, health and family are almost interchangeable, but I guess what seems obvious to me isn't for everybody, so go with the extended, explicit name). (BTW, my spell checker says "Child care" is one word: "Childcare").
4. `Collaboration`, `Communicatin`, `Enterprise software`(?!), `Expert networks`, `Human resources`, `Service relationship management`(?!?!?!?!), `Social networks`, `Staff/recruiting`, `Technology consulting` --> `BI, Consulting, Enterprise and Networking` (or just `Networking`... really all this new-age BS names that all mean, at the end of the day, "I know someone that can help you and I'll hook the two of you up for a finder's fee").

There are a lot more consolidation that can happen, but I've lost count and don't want to "double-book" any category so I'll stop here.

Once you start reducing and consolidating (like I suggested here, or using any scheme, basically) you'll see more sub-categories that can be eliminated naturally.

As was my suggestion on #296 maybe a "New company" form should include a "Category" drop-down menu with only those values as valid ones (of course, "-"/"N/A"/or simply `nil` is also an option). And just like in the country case, using this kind of drop-down will make both entering **and** filtering on these values much easier (both mentally, and to actually implement).

**Comment by doomspork** [comment]
@OmanF would you be interested in opening a PR that started the consolidation?

**Comment by OmanF** [comment]
Be happy to.
Just forked the repo and I'm having a hard time figuring out where some of the displayed industries originate from.

For example, neither `Blockchain & Finance`, `Cannabis` nor `Financial Technologies` are on the file `src/_data/indutries.yml`.

I'd happily take an axe to the correct file if you can just point me in the right direction.

**Comment by doomspork** [comment]
@OmanF I think we got mixed up here somewhere during a refactor.  I believe the industry list is actually pulled directly from `companies.yml`: https://github.com/doomspork/elixir-companies/blob/1cd694eda41c9151094252e72c9aa7d16fa7a90a/src/_data/companies.yml

https://github.com/doomspork/elixir-companies/blob/master/src/_plugins/generator.rb#L10

I'd love to discuss a way we can make this better for everyone.  There's 3-4 different projects now powered by this repo:  erlang-companies.org and kotlin-companies.com both for sure in addition to a julia companies and vue companies site (though I don't have those URLs)

**Comment by OmanF** [comment]
Pushed my first PR.
Like I said in the commit notes: I'm **not** saying this category list is optimal. I can see for myself how this may seem restricting to some, maybe it **is**... But some de-cluttering was a must at this time.

A future discussion can be held on what should be expanded and what can be further reduced.

As to a means of enforcing *an* agreed upon list, when one does emerge... my experience is that if you don't force your users to go the way you want (e.g. a form on the website with a drop-down, a webhook on any PR rejecting any `industry` not on the agreed upon list), there **will** be someone how deviates from the line.
By mistake or malice, doesn't matter, there will be deviations and we'll be facing the same problem again, only at a larger magnitude.

It really is that simple: agree upon a list. Enforce it (somehow). End of story.

As for the sites using this repo as their backend... they should follow suit or *clone* the repo and do their own thing.

**Comment by doomspork** [comment]
@michalmuskala  I'm going to close this for now but if you think this is still an issue I'm happy to discuss better ways to handle this data now that we're using Phoenix
