### ISSUE TITLE
Few lines on how elixir is used

### ISSUE THREAD

**Issue by aleinside** [doomspork/elixir-companies#44]
It would be nice to have some info on how elixir is used.

**Comment by doomspork** [comment]
@aleinside do you mean how each company uses Elixir?  I that could be a nice addition though I worry about it being too verbose.  Thoughts?

**Comment by aleinside** [comment]
@doomspork what do you think about a README file in relative directory, for example: 
`companies/<type>/<company name>/README`?

**Comment by avinoth** [comment]
:+1: It would be really good to have some info on how elixir is used, whether on the whole, or a part of system, if so which part of system and such.

**Comment by doomspork** [comment]
I agree it would be nice to know how it was being used, that was _kind_ of the idea behind the GitHub link.  If you're interested in knowing what they're doing you could check out their site or their GitHub repos.  

That said, I do have some reservations about a more substantiated write-up:

1. If it's perceived as required, it will turn away contributions.
1. I suspect a decent portion of the write-ups will be: "Using Phoenix".  Is that a value add?
1. But my biggest reservation: Many of the companies _do not_ want to disclose that information.  When I explored this before the bigger names were reluctant to publicly share how they were using it.

**Comment by doomspork** [comment]
@aleinside & @avinoth what do you think about using the new PR templates to suggest adding a note about usage?

The template could outline the format desired format while reminding them to alphabetize and include some mention of their usage.

**Comment by avinoth** [comment]
@doomspork Sounds good. Regarding your concerns over the companies might not want to share how elixir is being used, We aren't seeking any detailed explanation of how they've implemented but rather just how elixir fits into their ecosystem. An online would suffice.

Do you want me to create the template or do you have one in mind?

**Comment by doomspork** [comment]
@avinoth if you'd like to take a stab at putting together a template, @aleinsideand I  can provide some feedback and then merge.  Sound good?

Thanks for your interest and feedback :+1:

**Comment by avinoth** [comment]
Can we close this issue then?

**Comment by doomspork** [comment]
@avinoth yup :+1:
