### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-companies#450]
I'm ashamed of how little testing there is (read: none). This was intended to be quick-and-dirty but now that it's working, we should make it less dirty. The best place to start with that is going to be adding test coverage.

**Comment by tajchumber** [comment]
I came here to add an issue for this, but it's already here! hahah

**Comment by doomspork** [comment]
Sorry @tajchumber! I am very bad at writing tests early on 😆

**Comment by doomspork** [comment]
I've added a lot of test coverage. We need to get tests in there for Phoenix and if we want, the Schemas.  Do we want to close this issue and create new issues for the individual controller + view combos?

**Comment by zacck** [comment]
@doomspork  how about we make this an epic and list all the small tests to be added as tasks on this issue? especially for the schemas the Phoenix work?

**Comment by zacck** [comment]
@ricoh @WanjikuMac, this one has our names written all over it ... those changesets in the `schema` folder would be low hanging fruit
