### ISSUE TITLE
Allow users to edit existing companies and jobs

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-companies#458]
There is no way to update a company or a job after it has been posted, we need to provide a means to do this.

**Comment by brain-geek** [comment]
Is it still an issue? Seems like this has been implemented already in #466.

**Comment by doomspork** [comment]
@brain-geek would you like to help us with the project? I'd be happy to add you to the repo 😁

**Comment by brain-geek** [comment]
@doomspork Yep, that would be interesting. I don't expect to have a steady flow of contributions, more like having a peak every few months like in elixir school. 😄 

Also, would it be possible to get DB dump of industries, companies and jobs tables? For example, it would be helpful in debugging that paging issue.
