### ISSUE TITLE
Fix required Github permissions during authorization

### ISSUE THREAD

**Issue by tajchumber** [doomspork/elixir-companies#461]
From the authorization process, we only store email and nickname and email on db
![screenshot_2019-02-27 build software better together](https://user-images.githubusercontent.com/16062635/53523708-69dc4880-3ad5-11e9-883c-513cc2648ed8.png)

so we shouldn't ask for the full access to the profile and public repos but the information strictly neccessary.

**Comment by doomspork** [comment]
@tajchumber this sounds reasonable, would you like to update the perms?
