### ISSUE TITLE
Edit company has wrong heading at the top

### ISSUE THREAD

**Issue by tajchumber** [doomspork/elixir-companies#471]
When you edit a company the heading is "New Company", i think we should change it to "Edit Company" or the even the name of the company itself

<img width="728" alt="screenshot 2019-03-04 at 09 00 42" src="https://user-images.githubusercontent.com/16062635/53722229-ef0c8800-3e5c-11e9-8dda-d52441ecfbd0.png">

**Comment by gemantzu** [comment]
Closed by #475
