### ISSUE TITLE
Paging issues

### ISSUE THREAD

**Issue by brain-geek** [doomspork/elixir-companies#474]
Right now at http://elixir-companies.com/browse page there are 7 companies, 5 on http://elixir-companies.com/browse?page=2 and 8 on http://elixir-companies.com/browse?page=3 and (apparently) further. 

It's definitely a bug. But what is the reason why there are 8 companies per page initially? Wouldn't it be better with at least 16, or with endless scrolling?

**Comment by doomspork** [comment]
@brain-geek we picked 8 because it fit well on the page, we can absolutely up the count.

An error was just reported in AppSignal that may be related:

```elixir
ERROR 42P10 (invalid_column_reference) for SELECT DISTINCT, ORDER BY expressions must appear in select list

    query: SELECT DISTINCT c0."id", c0."blog", c0."description", c0."github", c0."location", c0."name", c0."url", c0."industry_id", c0."inserted_at", c0."updated_at", i1."id", i1."name", i1."inserted_at", i1."updated_at", j2."id", j2."title", j2."url", j2."company_id", j2."inserted_at", j2."updated_at" FROM "companies" AS c0 INNER JOIN "industries" AS i1 ON i1."id" = c0."industry_id" LEFT OUTER JOIN "jobs" AS j2 ON j2."company_id" = c0."id" WHERE (c0."name" ILIKE $1) OR (c0."name" ILIKE $2) OR (c0."name" ILIKE $3) OR (c0."name" ILIKE $4) OR (c0."name" ILIKE $5) ORDER BY LOWER(c0."name") LIMIT $6 OFFSET $7
```

```elixir
(ecto_sql) lib/ecto/adapters/sql.ex:590: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql) lib/ecto/adapters/sql.ex:523: Ecto.Adapters.SQL.execute/5
(ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
(ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
(scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:25: Scrivener.Paginater.Ecto.Query.paginate/2
(companies) lib/companies_web/controllers/company_controller.ex:14: CompaniesWeb.CompanyController.index/2
(companies) lib/companies_web/controllers/company_controller.ex:1: CompaniesWeb.CompanyController.action/2
(companies) lib/companies_web/controllers/company_controller.ex:1: CompaniesWeb.CompanyController.phoenix_controller_pipeline/2
```

When LiveView is out I think it would be awesome to redo everything 👍

**Comment by gemantzu** [comment]
I think #470 broke something here, links for companies by name initials do not work at all now.

**Comment by doomspork** [comment]
@brain-geek can you confirm this is still an issue? Looks to be resolved to me.

**Comment by gemantzu** [comment]
It is working properly now, #477 fixes this. Only question is if we want more than 8 companies to be displayed. Should we add a select on top with which users could pick how many they want?

**Comment by tajchumber** [comment]
We can add a select box on the side of pagination so that users can choose how many cards they want to see. Like this:

 <img width="179" alt="screenshot 2019-03-06 at 09 01 49" src="https://user-images.githubusercontent.com/16062635/53868710-88b76f00-3fee-11e9-85d6-50f0cfa2dc2a.png">

We should open a separate issue for this as it's entirely related.

**Comment by brain-geek** [comment]
I believe we should can bump it to at least 24, unless there are performance reasons to do it, for which I doubt. And add infinite scroll some time in the future.

**Comment by brain-geek** [comment]
Initial problem fixed by @doomspork , paging amounf being tweaked in #482 .
