### ISSUE TITLE
/hiring from google - Route exists but no method in controller

### ISSUE THREAD

**Issue by gemantzu** [doomspork/elixir-companies#476]
AppSingal shows this:
`function CompaniesWeb.CompanyController.hiring/2 is undefined or private`
which is possible if you come from google, where we have /hiring as a path (probably some seo left from the old website). This path exists in our router, but internally we have changed this functionality to work through `browse?type=hiring`.

**Comment by zacck** [comment]
Would a redirect here suffice?

**Comment by doomspork** [comment]
Yes, I think a redirect would be a good option here. Thank you @zacck 😁

**Comment by zacck** [comment]
Watch this 👁

**Comment by gemantzu** [comment]
@zacck thank you for your interest :) . Are you going to submit a PR for this? If yes, this is great, but if no, please let us know so we can go ahead and fix it ASAP because apparently a lot of people find themselves landing on an error page instead of a regular one. Thanks again :)

**Comment by zacck** [comment]
@gemantzu I did a thing :)
