### ISSUE TITLE
Gettext support

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-companies#493]
Is it worth us considering implementing Gettext into this project? It will serve as an example for the community in addition to allowing folks to provide translations if they so choose.

Thoughts @tajchumber, @gemantzu, @Nitrino?

**Comment by Nitrino** [comment]
I now think about it and planned to create an issue. 

I am the co-organizer of Moscow meetup and I often hear questions about how many and which companies in Russia write on the elixir. Therefore, I thought to launch elixir-companies.ru but found this project. 

I would like to think about how we can launch these projects together and allow local communities to be allocated to separate domains. For starters, I can add Gettext.

What do you think about this?

**Comment by doomspork** [comment]
We'd had tremendous success with translations over at [elixirschool/elixirschool](https://github.com/elixirschool/elixirschool/pulls) so I know the community is excited, I think gettext is a great addition! We should definitely kick that off.

I'm not sure I understand the need for extra domains though? Wouldn't we want a single domain for the most benefit to SEO so the resource is easier to find? I'd think we could set the locale based on the user's browser setting or with path (i.e. `elixir-companies.com/ru/`). There is also the possibility of subdomains but that can hurt SEO as I understand it.

Any thoughts @brain-geek, @gemantzu, and folks?

**Comment by Nitrino** [comment]
One more question:
What will we do with the description of the companies? They are filled in by users and only in one language.

**Comment by doomspork** [comment]
We have #497 and the work done in #495, closing this.
