### ISSUE TITLE
Localization of company descriptions

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-companies#500]
This is something brought up during the gettext work. How do we want to handle this if at all? I'm going to defer to @brain-geek and @gemantzu who have years of experience managing and providing translation for Elixir School.

**Comment by gemantzu** [comment]
I don't think we want to manage something like this. I can understand localizing the website, but translating descriptions? Who is going to manage this? Certainly not the "owner" of the company, they just care for the English description. We could ask with a poll though, if you believe there is enough interest about this.

**Comment by brain-geek** [comment]
I agree. Volunteeers won't be doing this, and company owners won't do as well - company from NY is not going to pay money to actual interpreters to translate their company description to russian, for example.

**Comment by Nitrino** [comment]
It seems the only option to leave the description in English.
But we need to be prepared that people will fill out descriptions in their own language.
Maybe we can use automatic translation via Google translate?

**Comment by doomspork** [comment]
It would be in an organizations best interest to provide the English translation themselves, if they don't, we can use their native description with the understanding most site visitors won't know what it says and likely won't look into them further
