### ISSUE TITLE
Browsing Companies by name should show companies alphabetically

### ISSUE THREAD

**Issue by gemantzu** [doomspork/elixir-companies#505]
Right now, browsing companies per name does not work properly, the companies with the correct starting letters are displayed but the order they are displayed is not alphabetical.

**Comment by tajchumber** [comment]
pushed this to master without a PR my bad! 👶 
this should be fixed now. Please let me know if this works for you @gemantzu @doomspork @brain-geek 😄

**Comment by gemantzu** [comment]
It seems fine to me. Thanx @tajchumber !
