### ISSUE TITLE
Company card only has the latest job.

### ISSUE THREAD

**Issue by gemantzu** [doomspork/elixir-companies#506]
If a company has more than one (approved jobs), they are not all displayed. Only the latest added one is shown.

**Comment by lccezinha** [comment]
@gemantzu I'll take a look.

**Comment by gemantzu** [comment]
thnx @lccezinha !

**Comment by lccezinha** [comment]
@gemantzu I'm afraid of showing the list of all jobs available for a company inside the box will put the description content about the company outside the div height.

Any suggestion about it? What the best approach to deal with this problem?

**Comment by gemantzu** [comment]
@lccezinha I don't think we have an issue with it. The card div scrolls after all. But that's a good question, should we possibly hide all jobs under an accordeon and expand on it only if clicked? What do you thing @doomspork / @tajchumber ?

**Comment by gemantzu** [comment]
closed by #507 ! Thank you @lccezinha !
