### ISSUE TITLE
Test capturing log but not compare the result log

### ISSUE THREAD

**Issue by joaothallis** [doomspork/elixir-companies#512]
https://github.com/doomspork/elixir-companies/blob/75c10e23bbf4e56896140454e49650c503d1f8bd/test/companies/jobs_test.exs#L26

Using https://hexdocs.pm/ex_unit/ExUnit.CaptureLog.html#capture_log/2 is only for check if has log?

**Comment by doomspork** [comment]
Howdy @joaothallis! You bring up a good point, we could be asserting against the logs here. We're doing that here: https://github.com/doomspork/elixir-companies/blob/b982e3c5a356df1f65d9409491eb45e862dfb22e/test/notify/console_test.exs#L12 which is the code ultimately called by these tests. Why I decided to use `capture_log/1` here without the assert was solely a matter of cleaning up the terminal output during test running.

Would you be interested in contributing a PR that would add assertions for the logs in the different tests we use `capture_log/1` and don't currently do so?

**Comment by joaothallis** [comment]
Yes, but you can use `@tag :capture_log` in every test or `@moduletag :capture_log` for cleaning up the terminal output during test running.

**Comment by doomspork** [comment]
@joaothallis that's a great suggestion 😁
