### ISSUE TITLE
Approvals / authentication urls not showing on mobile

### ISSUE THREAD

**Issue by gemantzu** [doomspork/elixir-companies#515]
While on mobile, i can't see the approvals and sign in / sign out buttons.

**Comment by doomspork** [comment]
I don't use mobile so this isn't a priority to me. @gemantzu you can tackle this one or we can close it. I'm not going to invest time in improving admin.

**Comment by tajchumber** [comment]
@gemantzu @doomspork I'll have a look a this one!

**Comment by doomspork** [comment]
You're the best @tajchumber!

**Comment by gemantzu** [comment]
Thank you @tajchumber , you are awesome!

**Comment by tajchumber** [comment]
@gemantzu can you give more details or a few screenshots of what's missing? and where?

**Comment by gemantzu** [comment]
![Screenshot_2019-05-06-20-19-40-162_org mozilla firefox](https://user-images.githubusercontent.com/4966172/57242559-77193480-703c-11e9-964f-6b4c2e6e3e41.png)
