### ISSUE TITLE
Add the country where the company is located

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-companies#53]
What about adding something like [BR] [US] [PL] in the right side of the name or something like that?

**Comment by doomspork** [comment]
I think that's a good suggestion @pragmaticivan :+1:

**Comment by pragmaticivan** [comment]
That's a big issue for me if I want to look for a job and just can work in USA hahaha

**Comment by doomspork** [comment]
Definitely.  I think it would be a good idea to create one of the new GitHub PR templates for this repo as discussed in #44.  If @aleinside or @avinoth don't have the time, feel free to put something together and open a PR for discussion :grinning:

**Comment by doomspork** [comment]
@pragmaticivan we now have a PR template for this repo, if you'd like to add a check box for including country code that would be great :+1:

**Comment by OmanF** [comment]
This will become redundant once #296 is implemented, but a template is a great interim solution.
