### ISSUE TITLE
Adding Digimondo to IoT category

### ISSUE THREAD

**Issue by h4cc** [doomspork/elixir-companies#94]
I would like to add my german company Digimondo, which is providing a IoT LoRaWAN Network. 

Should i create a new category "Internet of Things" for that?

**Comment by doomspork** [comment]
@h4cc I think that's be great!  I know some other Elixir IoT companies that should be coming out in the next few months.

**Comment by h4cc** [comment]
PR: https://github.com/doomspork/elixir-companies/pull/95
